




.build/mega2560/src/phytos.cpp : src/phytos.ino
	@mkdir -p .build/mega2560/src
	@echo [93msrc/phytos.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/mega2560/src/phytos.cpp
	@true

